name: CI

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  workflow_call:

jobs:
  build:
    name: Code standards & build
    runs-on: [self-hosted, linux, ci]
    timeout-minutes: 15

    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "📦 Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: "📦 Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "🔎 Lint code"
        run: pnpm run lint

      - name: "🚀 Build the project"
        run: pnpm run build
